apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apple
  template:
    metadata:
      labels:
        app: apple
    spec:
      containers:
      - image: okteto.dev/apple:latest
        name: apple
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "c080da2d-67f3-4da9-9e45-51c77493fa4d"
        - name: Vless_Path
          value: "/bde6t7dne7dn752rh46dyy45st"
        - name: Vmess_UUID
          value: "c080da2d-67f3-4da9-9e45-51c77493fa4d"
        - name: Vmess_Path
          value: "/cst8en9dsb4hy6db7s3hdyi67erth"
        - name: Share_Path
          value: "/v2link"
